### ISSUE TITLE
Add South Sudan SD Length 18

### ISSUE THREAD

**Issue by firehooper** [barend/java-iban#42]

**Comment by barend** [comment]
Hi firehooper,

Thank you for informing me that there have been changes to the IBAN Registry since the last release. I no longer work with IBAN's daily, so it's a little bit out of view and I missed the update. I'll prepare a new release of the library soon.

One request: please keep in mind that there's a human being on the other side. Your message is provides the necessary information, and it's helpful that you took the time to send it, but it's a bit light on social protocol. You absolutely do not have to write me a twenty page email, but I do appreciate some sort of basic greeting. Thanks.

Barend

**Comment by firehooper** [comment]
Hi @barend sorry for the brevity.  Thank you so much for this library!  This is a low priority as we use the SWIFT Ref files directly for most projects now to load the IBAN structure at runtime, but we started using this library before that.  This was mostly a TODO for myself or anyone depending on the library to not forget to submit a PR like this one: https://github.com/barend/java-iban/issues/7 .  So my intent was humane even if the written word did not indicate such.

**Comment by barend** [comment]
Hi @firehooper, thanks for the reply; all good. I just published version 1.10.1 to Maven Central that includes the IBAN spec for Sudan.
